#!/usr/bin/php
<?php
// Used by the new cvs to web to remove files (using expect and ftp
// command-line utils) from a server.
//
// USAGE:  remove_ftp username:password@machine:/folder file1 file2...
//
if( !defined('STDERR') ) define(STDERR, fopen('php://stderr', 'w') );

$remoteStuff = $_SERVER['argv'][1];
array_shift($_SERVER['argv']);
array_shift($_SERVER['argv']);

if (preg_match('/(.*):(.*)@(.*):(.*)/', $remoteStuff, $matches)) {
  $user = $matches[1];
  $password = $matches[2];
  $machine = $matches[3];
  $dir = $matches[4];
}
elseif (preg_match('/(.*)@(.*):(.*)/', $remoteStuff, $matches)) {
  $user = $matches[1];
  $password = "";
  $machine = $matches[2];
  $dir = $matches[3];
}
else {
  fwrite(STDERR, "$remoteStuff  must be:  user:password@machine:dir\nYou sent: {$_SERVER['argv']}\n");
  exit(1);
}

// Create list of FTP commands:
$ftpCommands = array();
$ftpCommands[] = "prompt off";
$ftpCommands[] = "cd \\\"$dir\\\"";

foreach ($_SERVER['argv'] AS $f) {
  if (substr($f, -1) == "/") {
    $ftpCommands[] ="cd \\\"$f\\\"";
    $ftpCommands[] ="mdelete *";
    $ftpCommands[] ="cd ..";
    $ftpCommands[] ="rmdir \\\"$f\\\"";
  } else {
    $ftpCommands[] ="delete \\\"$f\\\"";
  }
}
$ftpCommands[] = "exit";

// Use expect to run ftp (with password, if necessary):
$expectFilename = tempnam("/tmp", "expect_commands");
$expectFile = fopen($expectFilename, "w");
fwrite($expectFile, "set timeout 120\n");
fwrite($expectFile, "spawn -noecho ftp $machine\n");
$s = <<<EXPECTSTUFF
expect {
  "Name" { send "$user\r"; exp_continue }
  "Password:" { send "$password\r"; exp_continue }
  "password:" { send "$password\r"; exp_continue }
  "Permission denied" { exit 1 }
  "ftp>" { send "binary\r"  }
  timeout { send_error "ftp timeout\n"; exit 1 }
}  

EXPECTSTUFF;
fwrite($expectFile, $s);
foreach ($ftpCommands AS $command) {
  fwrite($expectFile, "expect {\n" );
  fwrite($expectFile, " \"ftp>\" { send -- \"$command\r\" }\n" );
  fwrite($expectFile, " \"Permission denied\" { exit 1 }\n" );
  fwrite($expectFile, " timeout { send_error \"ftp timeout\\n\"; exit 1 } \n");
  fwrite($expectFile, "}\n" );
}
fwrite($expectFile, "exit 0\n");
fclose($expectFile);

// To debug: un-comment out echo line, comment-out exec/unlink lines,
// then run expect manually to see what's going on:
//echo "/usr/bin/expect -d -b $expectFilename\n";
exec("/usr/bin/expect -b $expectFilename 2>&1", $output, $err);
unlink($expectFilename);

if ($err) {
   fwrite(STDERR, implode("\n", $output));
   exit($err);
}
?>
